<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro"
       name="ikor_cell" >

 
 <!-- Robotics system-->
  <!-- include -->
   <!-- ur5 -->
  <xacro:include filename="$(find acroba_resources)/urdf/ur5_macro.xacro" />

  <!-- instanciate -->
   <xacro:ur5_robot prefix="" joint_limited="false"/>

   <!-- Cylinder as a tool-->
   <xacro:property name="tool_length" value="0.15" />
   <xacro:property name="tool_radius" value="0.01" />

   <link name="tool_body1">
     <visual>
    <origin xyz="0 0 ${tool_length*0.5}" rpy="0 0 0"/>
    <geometry>
          <cylinder radius="${tool_radius}" length="${tool_length}"/>
      </geometry>
    <material name="tool_color">
        <color rgba="0.6 0.7 0.5 1"/>
      </material>
    </visual>
    <collision>
        <origin xyz="0 0 ${tool_length*0.5}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${tool_radius}" length="${tool_length}"/>
      </geometry>
    </collision>
    </link>

    <joint name="base_tool_joint" type="fixed">
        <parent link="tool0" />
        <child link = "tool_body1" />
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
    </joint>

  <xacro:property name="tiny_tool_length" value="0.07" />
   <xacro:property name="tinytool_radius" value="0.002" />
   <link name="tool_body2">
     <visual>
    <origin xyz="0 0 ${tiny_tool_length*0.5}" rpy="0 0 0"/>
    <geometry>
          <cylinder radius="${tinytool_radius}" length="${tiny_tool_length}"/>
      </geometry>
    <material name="tool_color">
        <color rgba="0.6 0.7 0.5 1"/>
      </material>
    </visual>
    <collision>
        <origin xyz="0 0 ${tiny_tool_length*0.5}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${tinytool_radius}" length="${tiny_tool_length}"/>
      </geometry>
    </collision>
    </link>

    
    <joint name="tiny_tool_joint" type="fixed">
        <parent link="tool_body1" />
        <child link = "tool_body2" />
        <origin xyz="0.0 0.0 ${tool_length}" rpy="${pi*0.5} 0.0 0.0" />
    </joint>

    <link name="end_tool"/>
    <joint name="end_tool_joint" type="fixed">
        <parent link="tool_body2" />
        <child link = "end_tool" />
        <origin xyz="0.0 0.0 ${tiny_tool_length}" rpy="0 0.0 0.0" />
    </joint>

  <link name="base_world"/>
  <joint name="base_world_joint" type="fixed">
    <parent link="base_world" />
    <child link = "base_link" />
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${pi*0.5}" />
  </joint>

  <link name="world" />
  <joint name="world_joint" type="fixed">
    <parent link="world" />
    <child link = "base_world" />
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${-pi*0.5}" /><!--z =0.616-->
  </joint>

<!-- Obstacles-->
<link name="table">
     <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
          <mesh filename="package://acroba_resources/meshes/icpe_case/bench.dae" scale="1 1 1"/>
      </geometry>
    <material name="bench_color">
        <color rgba="0.85 0.85 0.85 1"/>
      </material>
  </visual>
  <collision>
    <origin xyz="0 0 -0.02" rpy="0 0 0"/>
    <geometry>
      <box size="2 1 0.04"/>
    </geometry>
  </collision>
</link>

<joint name="table_joint" type="fixed">
    <parent link="base_world" />
    <child link = "table" />
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
</joint>

</robot>