<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro"
       name="precitek_cell" >

 
  <!-- include -->
  <xacro:include filename="$(find acroba_resources)/urdf/ur10_macro.xacro" />

  
  <!-- instanciate -->
  <xacro:ur10 prefix=""/>
  <link name="world" />

  <joint name="world_joint" type="fixed">
    <parent link="world" />
    <child link = "base_link" />
    <origin xyz="0 0 0" rpy="0.0 0.0 0.0" />
  </joint>


  <!-- sts support -->
  <link name="sts_support">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://acroba_resources/meshes/miscellaneous/STS/soporte_sts.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="support">
        <color rgba="0.6 0.6 0.6 1"/>
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://acroba_resources/meshes/miscellaneous/STS/soporte_sts.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>

  </link>
  <!-- sts link-->
  <xacro:property name="sts_length" value="0.182" /><!-- in reality 0.18045-->
   <xacro:property name="sts_diameter" value="0.138" /><!-- in reality 0.135-->
  <link name="sts_volume">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://acroba_resources/meshes/miscellaneous/STS/STS_centered.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 ${sts_length*0.5}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${sts_diameter*0.5}" length="${sts_length}"/>
      </geometry>
    </collision>

  </link>


  <joint name="support_joint" type="fixed">
    <parent link="tool0" />
    <child link = "sts_support" />
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
  </joint>

  <joint name="tool_joint" type="fixed">
    <parent link="sts_support" />
    <child link = "sts_volume" />
    <origin xyz="0.0 -0.036 0.09" rpy="-1.57079 0.0 0.0" />
  </joint>


  <link name="end_tool"/>
  <joint name="end_tool_joint" type="fixed">
    <parent link="sts_volume" />
    <child link = "end_tool" />
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
  </joint>

  <!--Obstacles-->
  
  <link name="floor">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="2 2 0.001"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
         <box size="2 2 0.001"/>
      </geometry>
    </collision>
  </link>

  <joint name="floor_joint" type="fixed">
    <parent link="world" />
    <child link = "floor" />
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
  </joint>


</robot>