
#-----------------------
# Docker config options
#  |-> X11: YES
#  |-> GPU: YES
#  |-> VG: WIN
#  |-> CELL: cell-config-roscon
#  |-> project-name: acroba-dev
#  |-> profile: acroba
#-----------------------
#
# (_GPU: gpu, _X: x, _VG: win, _NET: bridge)

# setting up the platform with gpu and x server support for profile acroba
# docker container project name = acroba-dev
# logs subfolder: 240617-163757
# setting up the platform with the cell config 'cell-config-roscon'
# looking for a docker config file for the cell 'cell-config-roscon'
# /home/acroba/cell-config/docker-compose.yml file found
# docker command GPU=gpu X=x VG_SETUP=win NET=bridge LOG_DIR=240617-163757 PROJECT=acroba-dev COMPOSE_PROFILES=x,acroba CELL=cell-config-roscon docker compose -f /home/loran/DEV/BFH/acroba/ACROBA-Platform-ROSConFR-SL/scripts/../docker/docker-compose.acroba.yml -f /home/loran/DEV/BFH/acroba/ACROBA-Platform-ROSConFR-SL/scripts/../docker/docker-compose.cell-config.yml -f /home/loran/.acroba/cell-config.yml
# final docker config:

name: acroba-dev
services:
  cell-config:
    command:
      - cell_config
      - vg
    container_name: acroba-dev-cell-config-roscon
    depends_on:
      roscore:
        condition: service_healthy
        required: true
      virtualgym:
        condition: service_started
        required: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
              count: -1
    environment:
      DISPLAY: :0
      ROS_MASTER_URI: http://roscore:11311
      SSH_PORT: "5025"
    image: acroba/cell-config
    networks:
      ros_network: null
    privileged: true
    volumes:
      - type: bind
        source: /home/loran/DEV/BFH/acroba/ACROBA-Platform-ROSConFR-SL/shared
        target: /home/acroba/share
        bind:
          create_host_path: true
      - type: volume
        source: data
        target: /home/acroba/data
        volume: {}
      - type: volume
        source: logs
        target: /home/acroba/logs
        volume: {}
      - type: bind
        source: /home/loran/DEV/BFH/acroba/ACROBA-Platform-ROSConFR-SL/.config/ssh/public
        target: /home/acroba/config/ssh
        bind:
          create_host_path: true
      - type: bind
        source: /home/loran/DEV/BFH/acroba/ACROBA-Platform-ROSConFR-SL/docker/scripts/start_sshd.sh
        target: /start_sshd.sh
        bind:
          create_host_path: true
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        bind:
          create_host_path: true
      - type: bind
        source: /dev
        target: /dev
        bind:
          create_host_path: true
      - type: bind
        source: /dev/bus/usb
        target: /dev/bus/usb
        bind:
          create_host_path: true
  initializer:
    command:
      - /bin/sh
      - -c
      - ' mkdir /home/acroba/logs/240617-163757/ &&  ln -sfn /home/acroba/logs/240617-163757/ /home/acroba/logs/latest; '
    entrypoint: []
    image: acroba/acroba-base-ros1
    networks:
      default: null
    volumes:
      - type: volume
        source: logs
        target: /home/acroba/logs
        volume: {}
    working_dir: /home/acroba/logs
  roscore:
    command:
      - roscore
    depends_on:
      initializer:
        condition: service_started
        required: true
    environment:
      ROS_LOG_DIR: /home/acroba/logs/latest/ros1/
    healthcheck:
      test:
        - CMD
        - /bin/bash
        - -c
        - source /opt/ros/noetic/setup.bash && rostopic list || exit 1
      timeout: 5s
      interval: 10s
      retries: 3
      start_period: 10s
      start_interval: 1s
    image: ros:noetic-ros-core
    networks:
      ros_network: null
    ports:
      - mode: ingress
        target: 11311
        published: "11311"
        protocol: tcp
    restart: on-failure
    volumes:
      - type: volume
        source: logs
        target: /home/acroba/logs
        volume: {}
  skills:
    profiles:
      - acroba
      - drl
    command:
      - roscon
    depends_on:
      cell-config:
        condition: service_started
        required: true
      roscore:
        condition: service_healthy
        required: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
              count: -1
    environment:
      DISPLAY: :0
      ROS_MASTER_URI: http://roscore:11311
      SSH_PORT: "5022"
    image: acroba/skills
    networks:
      ros_network: null
    volumes:
      - type: bind
        source: /home/loran/DEV/BFH/acroba/ACROBA-Platform-ROSConFR-SL/shared
        target: /home/acroba/share
        bind:
          create_host_path: true
      - type: volume
        source: data
        target: /home/acroba/data
        volume: {}
      - type: volume
        source: logs
        target: /home/acroba/logs
        volume: {}
      - type: bind
        source: /home/loran/DEV/BFH/acroba/ACROBA-Platform-ROSConFR-SL/.config/ssh/public
        target: /home/acroba/config/ssh
        bind:
          create_host_path: true
      - type: bind
        source: /home/loran/DEV/BFH/acroba/ACROBA-Platform-ROSConFR-SL/docker/scripts/start_sshd.sh
        target: /start_sshd.sh
        bind:
          create_host_path: true
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        bind:
          create_host_path: true
      - type: bind
        source: /dev
        target: /dev
        bind:
          create_host_path: true
  skills-vg:
    profiles:
      - acroba
      - drl
    command:
      - roscon
    depends_on:
      cell-config:
        condition: service_started
        required: true
      roscore:
        condition: service_healthy
        required: true
      virtualgym:
        condition: service_started
        required: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
              count: -1
    environment:
      DISPLAY: :0
      ROS_MASTER_URI: http://roscore:11311
      SSH_PORT: "5023"
    image: acroba/skills_vg
    networks:
      ros_network: null
    volumes:
      - type: bind
        source: /home/loran/DEV/BFH/acroba/ACROBA-Platform-ROSConFR-SL/shared
        target: /home/acroba/share
        bind:
          create_host_path: true
      - type: volume
        source: data
        target: /home/acroba/data
        volume: {}
      - type: volume
        source: logs
        target: /home/acroba/logs
        volume: {}
      - type: bind
        source: /home/loran/DEV/BFH/acroba/ACROBA-Platform-ROSConFR-SL/.config/ssh/public
        target: /home/acroba/config/ssh
        bind:
          create_host_path: true
      - type: bind
        source: /home/loran/DEV/BFH/acroba/ACROBA-Platform-ROSConFR-SL/docker/scripts/start_sshd.sh
        target: /start_sshd.sh
        bind:
          create_host_path: true
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        bind:
          create_host_path: true
      - type: bind
        source: /dev
        target: /dev
        bind:
          create_host_path: true
  taskplanner:
    profiles:
      - acroba
    depends_on:
      roscore:
        condition: service_healthy
        required: true
      skills:
        condition: service_started
        required: true
      skills-vg:
        condition: service_started
        required: true
      virtualgym:
        condition: service_started
        required: true
    environment:
      DISPLAY: :0
      ROS_MASTER_URI: http://roscore:11311
    image: acroba/taskplanner
    networks:
      ros_network: null
    volumes:
      - type: bind
        source: /home/loran/DEV/BFH/acroba/ACROBA-Platform-ROSConFR-SL/shared
        target: /home/acroba/share
        bind:
          create_host_path: true
      - type: volume
        source: data
        target: /home/acroba/data
        volume: {}
      - type: volume
        source: logs
        target: /home/acroba/logs
        volume: {}
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        bind:
          create_host_path: true
      - type: bind
        source: /dev
        target: /dev
        bind:
          create_host_path: true
      - type: bind
        source: /home/loran/DEV/BFH/acroba/ACROBA-Platform-ROSConFR-SL/.config/ssh/private
        target: /home/acroba/config/ssh
        bind:
          create_host_path: true
  virtualgym:
    profiles:
      - acroba
      - drl
    command:
      - roscon
      - win
    depends_on:
      roscore:
        condition: service_healthy
        required: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
              count: -1
    environment:
      DISPLAY: :0
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
      ROS_MASTER_URI: http://roscore:11311
      SSH_PORT: "5024"
    image: acroba/virtualgym
    networks:
      ros_network: null
    ports:
      - mode: ingress
        target: 10000
        published: "10000"
        protocol: tcp
    privileged: true
    volumes:
      - type: bind
        source: /home/loran/DEV/BFH/acroba/ACROBA-Platform-ROSConFR-SL/shared
        target: /home/acroba/share
        bind:
          create_host_path: true
      - type: volume
        source: data
        target: /home/acroba/data
        volume: {}
      - type: volume
        source: logs
        target: /home/acroba/logs
        volume: {}
      - type: bind
        source: /home/loran/DEV/BFH/acroba/ACROBA-Platform-ROSConFR-SL/.config/ssh/public
        target: /home/acroba/config/ssh
        bind:
          create_host_path: true
      - type: bind
        source: /home/loran/DEV/BFH/acroba/ACROBA-Platform-ROSConFR-SL/docker/scripts/start_sshd.sh
        target: /start_sshd.sh
        bind:
          create_host_path: true
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        bind:
          create_host_path: true
      - type: bind
        source: /dev
        target: /dev
        bind:
          create_host_path: true
networks:
  default:
    name: acroba-dev_default
  ros_network:
    name: acroba-dev_ros_network
    driver: bridge
volumes:
  data:
    name: acroba-dev_data
    external: true
  logs:
    name: acroba-dev_logs
    external: true
