# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: joint_a1

joint2_position_controller:
  type: position_controllers/JointPositionController
  joint: joint_a2

joint3_position_controller:
  type: position_controllers/JointPositionController
  joint: joint_a3

joint4_position_controller:
  type: position_controllers/JointPositionController
  joint: joint_a4

joint5_position_controller:
  type: position_controllers/JointPositionController
  joint: joint_a5

joint6_position_controller:
  type: position_controllers/JointPositionController
  joint: joint_a6


# Effort Controllers ---------------------------------------
joint1_effort_controller:
  type: effort_controllers/JointPositionController
  joint: joint_a1
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint2_effort_controller:
  type: effort_controllers/JointPositionController
  joint: joint_a2
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint3_effort_controller:
  type: effort_controllers/JointPositionController
  joint: joint_a3
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint4_effort_controller:
  type: effort_controllers/JointPositionController
  joint: joint_a4
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint5_effort_controller:
  type: effort_controllers/JointPositionController
  joint: joint_a5
  pid: {p: 10.0, i: 0.1, d: 10.0}

joint6_effort_controller:
  type: effort_controllers/JointPositionController
  joint: joint_a6
  pid: {p: 100.0, i: 0.01, d: 10.0}


# Trajectoria Forward Position Controllers ---------------------------------------
PositionJointInterface_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints: 
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6

  constraints:
    goal_time: 0.5                   # Override default
    stopped_velocity_tolerance: 0.05
    joint_a1: {trajectory: 0.1, goal: 0.1}
    joint_a2: {trajectory: 0.1, goal: 0.1}
    joint_a3: {trajectory: 0.1, goal: 0.1}
    joint_a4: {trajectory: 0.1, goal: 0.1}
    joint_a5: {trajectory: 0.1, goal: 0.1}
    joint_a6: {trajectory: 0.1, goal: 0.1}

  state_publish_rate:  25            # Override default
  action_monitor_rate: 30            # Override default
  stop_trajectory_duration: 0        # Override default